version: '3.8'

services:
  streamlit-app:
    build: .
    container_name: file-size-analyzer
    ports:
      - "8502:8501"
    volumes:
      - C:/:/host/c:ro
      - D:/:/host/d:ro
      - E:/:/host/e:ro
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped 