name: Build and Release Windows Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Create icon file (if not exists)
      run: |
        if (!(Test-Path "icon.ico")) {
          Write-Host "Creating placeholder icon..."
          # Create a simple placeholder icon or download one
          # For now, we'll skip icon creation
        }
        
    - name: Build executable
      run: |
        pyinstaller --clean main.spec
        
    - name: Create release archive
      run: |
        $version = $env:GITHUB_REF_NAME -replace 'v', ''
        $archiveName = "FileSizeAnalyzer-v$version-Windows.zip"
        
        # Create release directory
        New-Item -ItemType Directory -Path "release" -Force
        
        # Copy executable and create archive
        Copy-Item "dist\FileSizeAnalyzer.exe" "release\"
        
        # Create README for release
        @"
# File Size Analyzer v$version

## Windows Executable

This is the Windows executable version of File Size Analyzer.

### Features:
- 📁 Folder and file analysis
- 📊 Excel, PDF, HTML export
- 📈 Interactive charts
- 💾 Size optimization suggestions
- 🔍 Advanced filtering options

### Installation:
1. Download and extract the ZIP file
2. Run `FileSizeAnalyzer.exe`
3. No installation required - portable application

### System Requirements:
- Windows 10/11 (64-bit)
- No additional software required

### Usage:
- Select a folder to analyze
- Use filters to customize analysis
- Export reports in various formats
- View optimization suggestions

### Support:
For issues and questions, please visit the GitHub repository.
"@ | Out-File -FilePath "release\README.txt" -Encoding UTF8
        
        # Create ZIP archive
        Compress-Archive -Path "release\*" -DestinationPath $archiveName
        
    - name: Upload release assets
      uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: |
          FileSizeAnalyzer-v*-Windows.zip
          dist/FileSizeAnalyzer.exe
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: FileSizeAnalyzer-v*-Windows.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 