name: Build and Release Windows Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build executable
      run: |
        pyinstaller --clean main.spec
        
    - name: Create release archive
      run: |
        $version = $env:GITHUB_REF_NAME -replace 'v', ''
        $archiveName = "FileSizeAnalyzer-v$version-Windows.zip"
        
        # Create release directory
        New-Item -ItemType Directory -Path "release" -Force
        
        # Copy executable
        Copy-Item "dist\FileSizeAnalyzer.exe" "release\"
        
        # Create simple README
        $readmeText = "# File Size Analyzer v$version`n`n##Windows executable version. Extract and run FileSizeAnalyzer.exe"
        $readmeText | Out-File -FilePath "release\README.txt" -Encoding UTF8
        
        # Create ZIP archive
        Compress-Archive -Path "release\*" -DestinationPath $archiveName
        
    - name: Upload release assets
      uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: |
          FileSizeAnalyzer-v*-Windows.zip
          dist/FileSizeAnalyzer.exe
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: FileSizeAnalyzer-v*-Windows.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
